language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
install: true
addons:
  sonarcloud:
  organization: Cmarquardt17-github
  token:
    secure: d2a207f95b7f03e634cb8ca274e256c67ab4798b
script:
  ./gradle clean check sonarqube build
cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle
