language: node_js

node_js:
  - "iojs"
  - "7"
  
script:
  -ant build
  
notifications:
  email:
    recipients:
      - kaylaawheelerr@gmail.com
      - co.sluggett@gmail.com
      - christianmarquardt16@gmail.com
      - maxcarr12@gmail.com
    on_success: always 
    on_failure: always 
