language: python
install: true
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
addons:
  sonarcloud: 
  organization: cmarquardt17-github
  token:
    secure: d2a207f95b7f03e634cb8ca274e256c67ab4798b
script:
- sonar-scanner
cache:
  directories: "$HOME/.m2/repository $HOME/.sonar/cache $HOME/.gradle .gradle"
env:
  global:
  - secure: IFZti8ovhZg6J/h7YzT01jp/kzxScZ5WYH1WwvkRyer632BTW0pdkjlm1nbbkJ0ScwW890o6xfiViCiBdWAda49hno0AC2kcYm01HBQkZIecsvgiM8U3aHB2Ad6IqaUfLux0asLw0Ft+X4YxVM0vH1FSaQmr+p6RRvJzuEgZx8TJ5gMP3OzDeCM2eI2KKTOd2EwIz5xz98jXUco/3DCRq6N1TgXPxe65iB4BuIv+Kfu/vrm5R7qV5zOWlD9iCprOXmeqMkRN1ClgZzFJJRco2huEmKUhbOf61Yg2sKTpwYavSYNcb86v9QEJnD6pDg9hh5+ys9h3Jvo05pux/FBfhhipTzW+RFSou/yn2SCMo6K04XwmkHJND8xcC6N29UOmTLXIW6r4R+fNzmCueCHBII94Au1ldmE5t7QBEL6xI+KVTTIC3eM9i2szvLeXFL+rMbmT+1meGO2AfJamg7lyG80rCsKBmYabkiQphtz+RN+zS+wiV4kD40EQsg/06niji6VUFnbD32/7XmmkAl5oeQS8IeQh49m3bxAiB1CeSP3OkveqjcByRLEFUr4uKGfh47c+ZZsgTX1p5B28vTY2U9ivDbjJRR4g7GNk+y45nbmmVMGSY0/9QPO+00sJ+D8of+s33jKpd/m29s0hiSNSPuq/Z9WT68dMPgN5mDeR2GU=
  - secure: neLenvrjKzDsh9ba07uO3Vxgra5JX1MZ8JlAY1V2UIZ9xBrAiHujW6U7K8WN52c+IBwtRswcEjvB9uHzmTR+YXnoYjYpjsq0ERvFDElP+7oPOAHLrH0bW/JrNk0m1hoFC49KBn9rTTLGQTR9FkrPwy/P2LORshygipoGqXC3dAXoHiHePntwPDISGZk5z2VJ04sm+2SFLw2EPozp8bwOWCxy63OLmeLQTjBJwbxGf5CJEFuW3c9P7QKFxbRZ1+rvJ0IcCYI7ULLRPCipMpG5i7sWoLuMRRrwZEVXdgmKOyw2ProM7AcHjNvZC9996Sn+YjYFLj60BNjaaD0oyYtEAjXNlG4J8LlD2WWhohZ8e2Ehjr4D6xF+Tauc0u3H+mxQIgvKv1JxzOhKL2znndZxgHBQxOxdEiisBwv0WHrnKbp1YHAxpfJ6UoMlqONHd1QQbLaJomfs4/Vj8hoEUw1Eu4odIrYB9zMSRmID0Bn0fB+LZIjikk1rEv3tIt9wOq7YOS8rz4aiBq3uMyXOtxmND+U73whAsN1RZyar0UN7HzZbvkk6QL2W0IDXwyW3UWK7SQ1wBTjADNv+KBAzw+I+Di4u5+PWVVfFo/5RB5tUsPbjD14HafBsKXqg3SA+BhIIuBVx0JLiwATFERnBm6OsNnaBO9wbamlRwyTAYYEwn6Y=
dd:
  secure: cCjY1iDQkg09zCYX+zOBhrGJT8/qDG3BGnKmftFE8eHohcCFgL9+Reu/+u/ZO/3/nA0Nr/qRIhQBa4DlJCZLpgGFcUtdri9uECX3PWH7UMx4iaOnXmiEDF1HFZyOj/aCJvt87+RsmHDpN4qBOIv/cNSPL5yPR/DkxvevfmVjI7LMZAFTN8+2TBFX8aAHQjUe6JUkRHPS54dmO6MofZPKjM/a+Sa/VlQ9DIHFXRBJMBexSmqNPTiZkCmfvCV31vWH+Ul8MCtG6aMOAVMrKN3qbWMg0bvVQeR8HbaLdlGFV5szZCL003lZQer98TRvjhbDnHIyVchJbKdCzDvaK3rEGUqaG7p+y8BApv+B6/L9aJV6fQKYvaz4dze9xL7NJx6nV0kb429CM6AQSSImJ29hrVTLPQD7VZV2ZpT0V7iRdM5nvfHy8j5gNUdtaLpHVNVWCA9r3jhO5WICmkOkrU4dHFrAOkj36sCzvJ+qiZU2HzCbaqVlknHIjWQLz2YrSzELVHJTWDbzBhD4FXV0Sap12wGL3BWTcaRzNsCSGhSKY/pAM/rYPVF29mdDVYan9Wg8hxa0/KOGpqk1lJNBw2tJ491cNaZfCUvR8pb3N76z9xiS9oVs1ZZ/feXUzE1id+cZPDwvf77oaC1o2/Jl8Afib03fzyP59Sry595FPbKWQSA=
