language: python
install: true
python:
  - "3.3"
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  sonarcloud:
  organization: "cmarquardt17-github"
  token:
    secure: 970d6be993bb6dba192a834b922268b82f1091df

script:
  - sonar-scanner

cache:
  directories: "$HOME/.m2/repository $HOME/.sonar/cache $HOME/.gradle .gradle"

env:
  global:
    secure: gzjLgTJQUFOFrWO6MiNgsg2+ZaDSGTVrEW+At7EVLR9p1+1tVxVYOALFE6ZmSQekguIHc0xpk6dv6SNXkLqfSluwYlmI3bPBkfmXoCWZTKKcxQbo7uAF8okGpntmOs3XwvbQfWBzlF9YFZku+bdMh5Bmc8UdMFTaz9SlCNHgSqyJg0Dxtbt7kcKfmC7Oh3lSur3M/chV569R+UcHOZvpI3pvwQI7utuE79USd5uwPONH44DIj4oiZsHUfebsf8m0qgN1G1zAFLPgLHJS/XgbwdsvHAlbLjSd/N7PCoPc72l/mFqX/9n5DOsQHwGB+LlnbKKbk/BL46Ybf2eUsfQfgVEmVwr6AMj5rDJbuilfH17Zi7AndKK5gaaudSsDbFJI6PgJkFVAiJSGMjn8q89J/3IU3e9tCFOGv5Fkjk5sogN6wINfUjvGUd2qyBXMabaE4ydSUrLxFQy+QnVKPwhUbI9OuEQ8S2YfnXsF7rfh6CqhipbyvysHteVuOALtshy199CbxD66uuvSAS9LGsKOJqyu80hVCT1wLff3ZuACRwxri8hH07TTL+aZJdz91O7ViCwW+9beulisupVasuGC076TszxGQkwfUXGWGM6bijfL6HkfsmlIGYhOJUsvGTwkp4HhdUlq44aje6eXSwEXv1RFclzLg/rs2D9SsHm/8Y0=
