language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  sonarcloud:
  organization: Cmarquardt17-github
  token:
    secure: d2a207f95b7f03e634cb8ca274e256c67ab4798b
script:
  - sonar-scanner
cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle
